Files addede

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -23,11 +23,27 @@ jobs:
     steps:
       - name: Install AWS CLI
         run: |
+          echo "Downloading AWS CLI..."
           curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to download AWS CLI"
+            exit 1
+          fi
+
+          echo "Unzipping AWS CLI..."
+          unzip -q awscliv2.zip
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to unzip AWS CLI"
+            exit 1
+          fi
+
+          echo "Installing AWS CLI..."
           sudo ./aws/install
-          echo "Adding AWS CLI to PATH"
-          export PATH=$PATH:/usr/local/bin/aws
+          if [ $? -ne 0 ]; then
+            echo "Error: Failed to install AWS CLI"
+            exit 1
+          fi
+          echo "AWS CLI installed successfully"
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
